### ISSUE TITLE
Из Bitrix в retailCRM не передаётся новый статус заказа вместе с измененным статусом платежа

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/bitrix-module#100]
Возможно, проявляется только в режиме "Выгрузка заказов с помощью агента" - сейчас модуль работает в этом режиме.

По моим наблюдениям, проявляется, когда оплата происходит не сразу. Если оплата происходит достаточно быстро и попадает в передачу вновь созданного заказа, то статус заказа retailCRM верный.

На скриншотах видно, что информация об изменении платежа поступила в retailCRM, а о новом статусе - нет.

История заказа в Bitrix:
![image](https://user-images.githubusercontent.com/16384176/79749651-40553080-8318-11ea-8691-170a1edd79e8.png)
В дополнение, в 00:13 модуль retailCRM поменял статус заказа обратно на "Ждём оплату" (собственно это и обратило внимание на проблему).

История заказа в retailCRM:
![image](https://user-images.githubusercontent.com/16384176/79748113-8bba0f80-8315-11ea-8f19-7e9240db0bb8.png)

`assemblyOrderHistory.log`:
```
Array
(
    [TIME] => 2020-04-20 00:13:02
    [DATA] => Array
        (
            [id] => 28719
            [externalId] => 27768
            [managerId] => 27
            [site] => xxxxxxxxxxxxxxxxx
            [status] => waiting-for-payment
            [payments] => Array
                (
                    [32715] => Array
                        (
                            [id] => 32715
                            [type] => bank-card
                            [externalId] => 31960_5c0fd719161cc
                            [status] => Array
                                (
                                    [code] => paid
                                )
                        )
                )
        )
)
```

**Comment by iyzoer** [comment]
Да, все дело в выгрузке заказов с помощью агента. При этом режиме никакая информация о заказе обновлена не будет, этот момент описан в [документации](https://help.retailcrm.ru/Users/Bitrix#k3)

**Comment by pozdeiev** [comment]
Спасибо за ответ.
