### ISSUE TITLE
Возможны дубли в фиде

### ISSUE THREAD

**Issue by bestKomrad** [retailcrm/bitrix-module#190]
Есть вероятность, что при генерации фида в /classes/general/icml/RetailCrmICML.php:391 попадет пустой массив $products . Из за чего будут дубли торговых предложений в фиде.
Удалось такое поймать на версии модуля 5.2.6

**Comment by gwinn** [comment]
В ближайшем релизе приедет в маркетплейс, пока можно обновиться из репозитория
