### ISSUE TITLE
При обновлении перезаписывается options.xml

### ISSUE THREAD

**Issue by tolpekin** [retailcrm/bitrix-module#194]
При обновлении перезаписывается файл ./intaro.retailcrm/classes/general/config/options.xml. В результате слетают настройки кастомных полей
http://screenshot.irisdigital.ru/r0j8o_2021-04-01_16.11.47.png

**Comment by Neur0toxine** [comment]
Добрый день!

Уточните, пожалуйста, какая версия модуля была установлена у вас до обновления, а также версию модуля, на которую вы обновлялись.

**Comment by tolpekin** [comment]
Была установлена 2.4.6. Обновляли до последней 5.6.2

**Comment by Chazovs** [comment]
Добрый день!
Проверил обновление с 2.4.6 на 5.6.2. Обновление не привело к сбросу настроек в разделе "Cоответствия полей свойств заказа".
В 5.6.2 по сравнению с 2.4.6 в файле ./intaro.retailcrm/classes/general/config/options.xml есть только одно существенное изменение: мы разделили поле, которое называлось "Строение / корпус", на два отдельных: "Строение" и "Корпус". Соответственно, единственное ожидаемое изменение: появление пустого поля "Корпус". При  этом значение из поля "Строение/корпус" переносится в "Строение". Именно это я и наблюдал при тестировании.
К сожалению предоставленный вами скриншот в данный момент недоступен. Не могли бы вы его актуализировать? Возможно, он поможет нам воспроизвести проблему.

**Comment by Chazovs** [comment]
Дополнительно изучил вопрос. Возможность синхронизации кастомных полей была реализована в версии 2015 года (1.1.0). В данный момент этот функционал не поддерживается. Изменения, внесенные вручную в options.xml, могут быть затерты при обновлениях модуля. 
Перенести кастомные поля в новые версия модуля можно только вручную.

**Comment by tolpekin** [comment]
И как тогда быть, если нужна синхронизация кастомных полей?

**Comment by gwinn** [comment]
https://github.com/retailcrm/bitrix-module/wiki/%D0%9A%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0

**Comment by tolpekin** [comment]
Т.е. предложение заменить огромный файл кастомным?) Что в свою очередь "убьет" синхронизацию при последующем обновлении (гарантии обратной совместимости я нигде не вижу)

**Comment by gwinn** [comment]
Кастом классов не страдает при обновлении

**Comment by Chazovs** [comment]
Чтобы перенести кастомные поля, вам перед каждым обновлением модуля нужно скопировать из options.xml все ноды со свойством "group" равным "custom" в отдельный файл. После этого произвести обновление модуля. И уже после обновления ноды, хранящиеся во временном файле, скопировать обратно в options.xml.
