### ISSUE TITLE
Ошибка в работе orderHistory

### ISSUE THREAD

**Issue by daria-popova** [retailcrm/bitrix-module#25]
Столкнулись с ситуацией, когда апи возвращает на первой странице истории пустой массив, а на следующих есть изменения (видимо за счет отбрасывания изменений о множественных оплатах)
http://joxi.ru/n2Y00nkFo13bYm

Этот код в такой ситуации останавливается и дальше загрузка не идет
https://github.com/retailcrm/bitrix-module/blob/master/intaro.retailcrm/classes/general/history/RetailCrmHistory.php#L303

В условии нужно проверять не пустой массив, а что текущая страница равна последней

**Comment by gwinn** [comment]
Внедрено
