### ISSUE TITLE
Новый генератор каталога.

### ISSUE THREAD

**Issue by AizekCrm** [retailcrm/bitrix-module#304]
Добрый день, после обновления модуля до последней версии 6+, у нас перестали работать кастомизации с файла RetailCrmICML.php, судя по файлу export_run.php он нигде не используется в новой генерации кроме его подключения в include.php . Как нам кастомизировать генерацию на данный момент?

**Comment by uryvskiy-dima** [comment]
Здравствуйте, генерация каталога была оптимизирована в версии 5.8.1, при обновлении на эту версию или 6.x кастомизация каталога через RetailCrmICML.php не работает. На данный момент мы прорабатываем возможность кастомизировать генерацию ICML каталога для версий модуля 6.x

**Comment by AizekCrm** [comment]
Хорошо. Спасибо за обратную связь.

**Comment by gwinn** [comment]
#306 внедрено
