### ISSUE TITLE
Кастомные поля в настройках модуля

### ISSUE THREAD

**Issue by qweik** [retailcrm/bitrix-module#318]
Исправил работу с кастомными полями в настройках
https://pastebin.com/zt6bqrny

<img width="503" alt="image" src="https://github.com/retailcrm/bitrix-module/assets/14828893/07b1d6b0-0837-48fa-98d4-eb20140dbd5d">
<img width="802" alt="image" src="https://github.com/retailcrm/bitrix-module/assets/14828893/6c0dd6f5-61da-4f39-8223-8fe3505d12f6">
<img width="1626" alt="image" src="https://github.com/retailcrm/bitrix-module/assets/14828893/9d10d8ce-4d27-4407-9527-5165ab4e7b2d">

<img width="1012" alt="image" src="https://github.com/retailcrm/bitrix-module/assets/14828893/ff4155d0-f9d2-496f-b253-0e678c9df0fc">
<img width="1626" alt="image" src="https://github.com/retailcrm/bitrix-module/assets/14828893/7ff7d15a-188a-4d84-8e2e-8e6b11bee929">

**Comment by uryvskiy-dima** [comment]
Добрый день, спасибо за предоставленное решение, но на основе проведенного ранее анализа, мы приняли решение о глобальной переработке данного функционала в модуле.
