### ISSUE TITLE
Ошибка при отключенном модуле Сайты 24 (landing)

### ISSUE THREAD

**Issue by FireCardinal** [retailcrm/bitrix-module#322]
При отключенном модуле Сайты 24 (landing) невозможно перейти в настройки модуля RetailCrm. Делается mysql запрос и происходит обращение к несуществующей таблице.
![image](https://github.com/retailcrm/bitrix-module/assets/1117303/41bc5a3d-a19f-426a-82b7-108b39268967)

**Comment by uryvskiy-dima** [comment]
Здравствуйте, модуль **Сайты 24 (landing)** является обязательным для корректной работы модуля RetailCRM с версии [6.4.3](https://github.com/retailcrm/bitrix-module/releases/tag/v6.4.3).

**Comment by Ipatov** [comment]
Модуль Сайты 24 (landing) имеет уязвимость открытую. Его из-за этого отключают. Битрикс выпускал обновление с фиксом, но это обновление не закрыло уязвимость.

**Comment by uryvskiy-dima** [comment]
Здравствуйте, произвели анализ проблемы с уязвимостью [Сайты 24 (landing)](https://www.1c-bitrix.ru/vul/18645386/). Приняли решение переработать функционал валидации валют, таким образом, чтобы не использовать модуль **Сайты 24 (landing)**. На следующей неделе выпустим обновление с исправлением.

**Comment by uryvskiy-dima** [comment]
Исправление готово, в [маркетплейсе](https://marketplace.1c-bitrix.ru/solutions/intaro.retailcrm/) будет доступно 13.12.23
