### ISSUE TITLE
Ошибка при формировании адреса из разных полей (детально)

### ISSUE THREAD

**Issue by Isa3v** [retailcrm/bitrix-module#328]
![image](https://github.com/retailcrm/bitrix-module/assets/30827684/70ea1eeb-217b-4a94-baa1-c90304d21c4c)

Обновление ref #315 поломало отправку адреса из отдельных полей, т.к ранее он собирался таким образом: 
```
if (!empty($prop['VALUE'][0])) {
    $order['delivery']['address'][$search] = $prop['VALUE'][0];
}
```
Конкретно не отправляет улицу, дом, квартиру.
                    
[intaro.retailcrm/classes/general/order/RetailCrmOrder_v5.php](https://github.com/retailcrm/bitrix-module/commit/7404105dec1187129fd05218fdc7d06a7b35c83e#diff-88d02f8f57eefa02ea41138c81a653bbda10b95c46ed22139877ae81bef7eb35)

**Comment by uryvskiy-dima** [comment]
Здравствуйте, о проблеме с синхронизацией адресов нам известно. На следующей неделе выпустим обновление с исправлением.

**Comment by uryvskiy-dima** [comment]
Здравствуйте, решение подготовили, мы изменили логику маппинга и улучшили синхронизацию полей, но нам необходимо произвести дополнительное тестирование, поэтому выпустить релиз сможем после **новогодних праздников.**
