### ISSUE TITLE
Повторное применение скидки

### ISSUE THREAD

**Issue by gitlobster** [retailcrm/bitrix-module#337]
Если в црм на товар указать скидку, то в битриксе проставится новая цена. Однако при любых изменениях заказа в битриксе, информация вновь отправляется в црм с ценой с учетом скидки, на которую црм вновь ее применяет.

Это ошибка или можно как-то с галок сделать, чтобы такого не проиходило?

**Comment by uryvskiy-dima** [comment]
Здравствуйте, зафиксировал ошибку, по срокам решения на данный момент сориентировать не могу, следите за обновлениями модуля.

**Comment by uryvskiy-dima** [comment]
Здравствуйте, сегодня добавлю версию с исправлением на маркетплейс.
