### ISSUE TITLE
externalId задается через суммирование +=

### ISSUE THREAD

**Issue by drNovikov** [retailcrm/bitrix-module#354]
https://github.com/retailcrm/bitrix-module/blob/992162c01e4c46cdfe23d87208145156f1cb5e53/intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php#L972

`externalId` задается через суммирование `+=`, а не через простое присваивание `=`

**Comment by uryvskiy-dima** [comment]
Привет, подскажи, у тебя возникают какие-либо ошибки из-за этого ?

**Comment by drNovikov** [comment]
> Привет, подскажи, у тебя возникают какие-либо ошибки из-за этого ?

Привет, ошибок из-за этого не заметил. Наткнулся, когда дебажил странности с работой промокодов, которые в результате не от модуля ритейла. Удивился суммированию айдишников :)

**Comment by uryvskiy-dima** [comment]
Слил исправление, была допущена опечатка, которая не мешала работе модуля :)
