### ISSUE TITLE
При удалении модуля выкидывает Class "Intaro\RetailCrm\Component\Advanced\LoyaltyInstaller" not found

### ISSUE THREAD

**Issue by drNovikov** [retailcrm/bitrix-module#358]
https://github.com/retailcrm/bitrix-module/blame/a83ff3cc6b1335afe6c3e3ec1618f5a899f3d35a/intaro.retailcrm/install/index.php#L1322

При удалении модуля выкидывает исключение:
```
Class "Intaro\RetailCrm\Component\Advanced\LoyaltyInstaller" not found (0)
/home/bitrix/www/bitrix/modules/intaro.retailcrm/install/index.php:1328
#0: intaro_retailcrm->DoUninstall
        /home/bitrix/www/bitrix/modules/main/admin/partner_modules.php:250
#1: require_once(string)
        /home/bitrix/www/bitrix/admin/partner_modules.php:2
```

Чтобы исправить, пришлось добавить в `DoUninstall()`
`require_once($this->INSTALL_PATH . '/../lib/component/advanced/loyaltyinstaller.php');`

**Comment by Kocmonavtik** [comment]
Здравствуйте. Подготовил решение проблемы. Обновим модуль в ближайшее время
