### ISSUE TITLE
Поломка заказа со скидкой от модуля Maxma у аутентифицированных пользователей при включенной опции передачи корзины

### ISSUE THREAD

**Issue by drNovikov** [retailcrm/bitrix-module#374]
Обнаружили непредвиденный побочный эффект этого метода, приводящий к проблемам на бизнес-уровне.

Описание проблемы:
 - Установлены последние версии модулей RetailCRM и Maxma.
 - Модуль MAXMA применяет скидку по промокоду.
 - При оформлении заказ ломается:
 - В CRM уходят неверные данные.
 - В админке битрикса цена товара в заказе оказывается без скидки
 - Онлайн-оплата ломается т.к. в API онлайн-кассы уходит неверная цена (без учета скидки)

Это случается только если пользователь аутентифицирован.

Проблема исчезает, если отключить функцию передачи корзины.

При включенной опции передачи корзины регистрируется обработчик `RetailCrmEvent::onChangeBasket` для битриксового события `OnSaleBasketSaved` . Если пользователь не аутентифицирован, он ничего не делает. У залогиненных же вызывается функция `RetailCrmCart::getBasketArray` -- если закомментировать -- проблема не возникает.

https://github.com/retailcrm/bitrix-module/blob/41257b9d7cd02775d409df4dadb77e76c62825df/intaro.retailcrm/classes/general/events/RetailCrmEvent.php#L135

После оооочень долгого дебага нашли, что если закомментировать вот эту строчку, проблема исчезает.

https://github.com/retailcrm/bitrix-module/blob/41257b9d7cd02775d409df4dadb77e76c62825df/intaro.retailcrm/classes/general/cart/RetailCrmCart_v5.php#L150

В этой строке меняется объект класса `Bitrix\Sale\Internals\Fields`. Видимо, при этом и случается побочный эффект, приводящий к поломке заказа.

В документации для разработчиков [указано](https://dev.1c-bitrix.ru/api_d7/bitrix/sale/classes/internals/index.php):

> Важно! Прямое использование данных классов не рекомендуется и совместимость не гарантируется

Видимо, по причине недокументированного и плохо предсказуемого поведения.

Техподдержка не помогла, кивает на модуль Maxma. Пришлось временно отключить функциональность передачи корзин в систему.

Предлагаю переделать эту функцию так, чтобы не менять объект `$itemFields` -- если надо собрать массив для дальнейшей отправки в API -- получить данные через `$itemFields->getValues()` и уже дальше передавать в `RetailCrmCart::handlerCart($arBasket);`

**Comment by drNovikov** [comment]
> Вы можете самостоятельно подготовить и отправить Pull Request с нужными изменениями.

https://github.com/retailcrm/bitrix-module/pull/376/files

**Comment by uryvskiy-dima** [comment]
PR слил в master, в течение дня добавлю новую версию на маркетплейс.

**Comment by drNovikov** [comment]
> PR слил в master, в течение дня добавлю новую версию на маркетплейс.

Спасибо, коллеги!
