### ISSUE TITLE
Точка вызывает ошибку при обмене

### ISSUE THREAD

**Issue by bestKomrad** [retailcrm/bitrix-module#42]
Если со стороны retailCrm в поле "Город" поставить точку, то во время обмена с битриксом из за отсуствия проверки на пустоту строки, \Bitrix\Sale\Location\Search\Finder::find падает на Assert::expectStringNotNull . Получилось повторить два раза со строкой, которая содержит только точку. https://github.com/retailcrm/bitrix-module/blob/6b98bf0ee2d2ced8e37a05775122c811a00d87ca/intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php#L565

**Comment by iyzoer** [comment]
В версии 2.3.6 добавили обработку исключения.
