### ISSUE TITLE
История

### ISSUE THREAD

**Issue by ilyasavitski** [retailcrm/bitrix-module#43]
Не работает история. Подскажите, пожалуйста, как настроить агента или крон для работы истории?

**Comment by iyzoer** [comment]
Агент вообще не запускается или при запуске агента есть какие то ошибки? Как перевести агенты на выполнение по крону можете узнать [здесь](https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=43&LESSON_ID=2943&LESSON_PATH=3913.4776.4620.4978.2943)

**Comment by ilyasavitski** [comment]
Агента вообще не было - пришлось руками добавлять) Вопрос закрыт.
