### ISSUE TITLE
RetailCrmUser::customerEdit(): запись в лог несвоевременна

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/bitrix-module#75]
В указанном методе в блоке
```php
if ($found) {
    //...
}
```
производится запись в лог `$log->write($customer, 'customerSend');` - на мой взгляд, рано, т.к. далее происходит вызов `retailCrmBeforeCustomerSend()`, который модифицирует `$customer` или отменяет передачу. Предалагаю раземестить логирование непосредственно перед вызовом `RCrmActions::apiMethod()`, а-то лог вводит в заблуждение.

**Comment by Evgeniy-Goroh** [comment]
Да, в ближайщем обновлении модуля добавим логирование неносредственно перед отправкой
