### ISSUE TITLE
Feature request: передавать в функции retailCrm*CustomerSave($customer) пользовательские поля ($customer[customFileds])

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/bitrix-module#76]
Сейчас приходится ходить за пользовательскими полями в API CRM - хотелось бы обойтись без этого.

**Comment by Evgeniy-Goroh** [comment]
В модуле присутствует дополнительный функционал, позволяющий модифицировать данные, приходящие из системы и уходящие в нее. Для этого в файле init.php нужно описать нужную функцию и произвести требуемые изменения данных. 
Для отправки кастомных полей из CMS в CRM нужно использовать дополнительные возможности https://help.retailcrm.ru/Users/Bitrix#k6
retailCrmBeforeCustomerSend — модификация данных клиента перед отправкой в систему.

**Comment by pozdeiev** [comment]
Я тут веду речь про передачу данных в обратную сторону - из CRM в CMS.

**Comment by gwinn** [comment]
https://github.com/retailcrm/bitrix-module/commit/b81cd1ccc4706510ce4e2fde5e909b5b6a4c8dea
