### ISSUE TITLE
RestNormalizer не позволяет опустошить значение поля 'date'

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/bitrix-module#77]
Например, если в `retailCrmBeforeOrderSend()` задать значение
```php
$order['delivery']['date'] = '';
```
то нормализер перепишет текущей датой. Это не то, чего ожидаешь, когда есть цель убрать дату доставки.

**Comment by Evgeniy-Goroh** [comment]
Файл RestNormalizer.php можно модифицировать без потерь при обновлении модуля, он должен находиться в  /php_interface/retailcrm/RestNormalizer.php

**Comment by pozdeiev** [comment]
У этой возможности есть вроде бы некритичная проблема в том, что она не следует текущей рекомендации Bitrix размещать такие кастомизации в `/local`. Но заказчик выдвинул требования, что все правки должны размещаться в `/local`, и в итоге проблема стала критичной.

**Comment by pozdeiev** [comment]
Возможность "скопируй в `/bitrix/php_interface/retailcrm` и модифицируй" имеет как минимум пару изъянов.
1. Она не следует рекомендации Bitrix размещать кастомизации в `/local`.
2. Копирование файла "замораживает" класс, он перестаёт развиваться вместе с оригинальным кодом модуля, что в будущем может привести к фатальным ошибкам.

Поэтому не хотелось бы прибегать к этой возможности без острой необходимости.

Можно ожидать изменение поведения оригинального `RestNormalizer::setDateTime()` относительно пустой даты?

**Comment by gwinn** [comment]
Пока нет
