### ISSUE TITLE
RetailCrmHistory::orderHistory(): буксует, когда $orderPayment->getId() не возвращает значение

### ISSUE THREAD

**Issue by pozdeiev** [retailcrm/bitrix-module#81]
А `$orderPayment->getId()` так может... (Даже не пытаюсь понять, почему он так может.)
В следствие чего в блоке `if (!empty($newHistoryPayments)) { ... }` вызов `\Bitrix\Sale\Internals\PaymentTable::update($paymentId, array('XML_ID' => ''))` приводит к исключению и прерыванию работы программы, не записывается `sinceId`, в следующий раз обработчик начинает с того же места и так до бесконечности.

**Comment by Evgeniy-Goroh** [comment]
Когда не записывается sinceId, значит есть ошибки в обработке истории и это логично, значит дальнейшая загрузка истории невозможна,
Рассмотрим данную ситуацию

**Comment by pozdeiev** [comment]
По поводу логичности спору нет. Я говорю о том, что в коде не проверяется значение `$orderPayment->getId()`, которое может быть пустым, что несколькими строками ниже приводит к фатальному исключению.
