### ISSUE TITLE
При смене физ.лица на юр.лицо в crm в битрикс не приходят юридические реквизиты

### ISSUE THREAD

**Issue by Revialas** [retailcrm/bitrix-module#84]
Как мне кажется это вызвано тем, что на строке 467 (orderHistory) выставляется `$propsRemove = true;` Далее на 520 строке идет замена заказа сформированного assemblyOrder на весь заказ полученный из crm `$order = $orderCrm['order'];` А на 612 строке проверка `if (array_key_exists($key, $order))` не проходит, так как массив $order содержит весь заказ, а там такие параметры как к примеру инн хранятся в виде `order[contragent][INN]`, сама проверка же сделана для массива `assemblyOrder  `где инн хранится сразу без `[contragent]`
P.S. если поменять физлицо на юрлицо, дать отработать истории, а потом внести юр реквизиты то всё будет нормально. Что косвенно подтверждает мою теорию насчет проблемы в замене массива заказа
P.P.S. Примерная говнокодерское расширение if решает проблему
```
if (array_key_exists($key, $order)) {
    $somePropValue = $propertyCollection->getItemByOrderPropertyId($propsKey[$orderProp]['ID']);
    self::setProp($somePropValue, $order[$key]);
}elseif(array_key_exists($key, $order['contragent'])){
    $somePropValue = $propertyCollection->getItemByOrderPropertyId($propsKey[$orderProp]['ID']);
    self::setProp($somePropValue, $order['contragent'][$key]);
}
```

**Comment by gwinn** [comment]
https://github.com/retailcrm/bitrix-module/commit/17c853144c1f5158aa8528ab33095eac6fb14c80
