### ISSUE TITLE
В генерации icml нету сброса закупочной цены (purchasePrice)  при её отсутствии

### ISSUE THREAD

**Issue by Revialas** [retailcrm/bitrix-module#92]
https://github.com/retailcrm/bitrix-module/blob/d475c95a010336b2a02111d9b201368ea65d0f6d/intaro.retailcrm/classes/general/icml/RetailCrmICML.php#L624

Здравствуйте.
> purchasePrice — закупочная цена торгового предложения (товара), не является обязательной; При отсутствии тега в файле значение не будет сбрасываться; Закупочная цена может быть целой или дробной с точностью до 2 знаков после запятой в промежутке от 0 до 99 999 999;

Поэтому логично было бы сделать сброс закупочной цены на 0 если она не указана, т.к. возможны случаи что цена ранее была указана, попала в црм, а потом её удалили из битрикс. И данные в crm будут ложные и могут вводить в заблуждение менеджеров.
```
if ($arOffer['PURCHASE_PRICE'] && $this->loadPurchasePrice) {
    $offer .= "<purchasePrice>" . $this->PrepareValue($arOffer['PURCHASE_PRICE']) . "</purchasePrice>\n";
}else{
    $offer .= "<purchasePrice>0</purchasePrice>\n";
}  
```

**Comment by gwinn** [comment]
Добавлена опция позволяющая включить желаемое поведение, релиз 5.2.6 бета
